name: Build Bakers Dozen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        # Cross-platform build
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # Download openFrameworks
      - name: Setup openFrameworks
        uses: nandenjin/openframeworks-action@v1
        with:
          command: setup-of
          of_version: 0.12.0

      # Checkout your repo under `apps`
      - uses: actions/checkout@v4
        with:
          path: 'apps/Bakers-Dozen'

      # Setup your project with projectGenerator
      - name: Generate project
        uses: nandenjin/openframeworks-action@v1
        with:
          command: projectgenerator
          project_root: 'apps/Bakers-Dozen/Bakers Dozen'

      # (Required for MSBuild on Windows)
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
        if: startsWith(matrix.os, 'windows')

      # Build your project
      - name: Build
        uses: nandenjin/openframeworks-action@v1
        with:
          command: build
          project_root: 'apps/Bakers-Dozen/Bakers Dozen'
