name: Build Bakers Dozen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        choco install visualstudio2017buildtools --version 15.9.35 -y
        choco install visualstudio2017-workload-vctools -y
        choco install glew -y
        choco install glfw -y
        choco install freeimage -y

    - name: Download OpenFrameworks
      run: |
        curl -L https://github.com/openframeworks/openFrameworks/archive/refs/tags/0.11.2.zip -o openFrameworks.zip
        mkdir C:\openFrameworks
        tar -xf openFrameworks.zip -C C:\openFrameworks --strip-components=1
        # Manually downloading dependencies if needed (example for GLEW)
        curl -L https://github.com/nigels-com/glew/archive/refs/tags/2.1.0.zip -o glew.zip
        mkdir C:\glew
        tar -xf glew.zip -C C:\glew --strip-components=1
        # Repeat similar steps for other dependencies if needed

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build solution
      run: msbuild "Bakers Dozen/Bakers Dozen/Bakers Dozen.vcxproj" /p:Configuration=Release
      env:
        OF_ROOT: C:\openFrameworks
